// Implementation limits an application may size its work by. Recording on
// one driver and replaying on another only works if the recorded program saw
// limits the replay driver also has.
#pragma once

static const unsigned gles_caps[] = {
    0x0D33, /* GL_MAX_TEXTURE_SIZE */
    0x0D3A, /* GL_MAX_VIEWPORT_DIMS (2 values) */
    0x8073, /* GL_MAX_3D_TEXTURE_SIZE */
    0x851C, /* GL_MAX_CUBE_MAP_TEXTURE_SIZE */
    0x88FF, /* GL_MAX_ARRAY_TEXTURE_LAYERS */
    0x84E8, /* GL_MAX_RENDERBUFFER_SIZE */
    0x8D57, /* GL_MAX_SAMPLES */
    0x8824, /* GL_MAX_DRAW_BUFFERS */
    0x8CDF, /* GL_MAX_COLOR_ATTACHMENTS */
    0x8869, /* GL_MAX_VERTEX_ATTRIBS */
    0x8872, /* GL_MAX_TEXTURE_IMAGE_UNITS */
    0x8B4C, /* GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS */
    0x8B4D, /* GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS */
    0x8DFB, /* GL_MAX_VERTEX_UNIFORM_VECTORS */
    0x8B4A, /* GL_MAX_VERTEX_UNIFORM_COMPONENTS */
    0x8DFD, /* GL_MAX_FRAGMENT_UNIFORM_VECTORS */
    0x8B49, /* GL_MAX_FRAGMENT_UNIFORM_COMPONENTS */
    0x8DFC, /* GL_MAX_VARYING_VECTORS */
    0x8B4B, /* GL_MAX_VARYING_COMPONENTS */
    0x9122, /* GL_MAX_VERTEX_OUTPUT_COMPONENTS */
    0x9125, /* GL_MAX_FRAGMENT_INPUT_COMPONENTS */
    0x8A2B, /* GL_MAX_VERTEX_UNIFORM_BLOCKS */
    0x8A2D, /* GL_MAX_FRAGMENT_UNIFORM_BLOCKS */
    0x8A2E, /* GL_MAX_COMBINED_UNIFORM_BLOCKS */
    0x8A2F, /* GL_MAX_UNIFORM_BUFFER_BINDINGS */
    0x8A30, /* GL_MAX_UNIFORM_BLOCK_SIZE */
    0x8A31, /* GL_MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS */
    0x8A33, /* GL_MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS */
    0x8C8A, /* GL_MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS */
    0x8C8B, /* GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS */
    0x8C80, /* GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS */
    0x84FD, /* GL_MAX_TEXTURE_LOD_BIAS */
    0x8D6B, /* GL_MAX_ELEMENT_INDEX */
    0x80E8, /* GL_MAX_ELEMENTS_INDICES */
    0x80E9, /* GL_MAX_ELEMENTS_VERTICES */
    0x8904, /* GL_MIN_PROGRAM_TEXEL_OFFSET */
    0x8905, /* GL_MAX_PROGRAM_TEXEL_OFFSET */
};
